Session/4
KaitoKudou/Yumemi-iOS-Training pull request #3
Opened 2022-03-29 08:51 UTC by KaitoKudou

# やったこと
- `static func fetchWeather(_ jsonString: String) throws -> String`を使い、Viewに最低気温と最高気温を表示

# 実行画面
<img width="370" alt="スクリーンショット 2022-03-29 17 20 37" src="https://user-images.githubusercontent.com/40165303/160566715-ef5a728c-c95b-4f01-a50b-0597135a254f.png">

2022-03-30 04:38 UTC, novr requested changes

2022-03-30 04:38 UTC, novr commented on Yumemi-ios-training/Yumemi-ios-training/Model/WeatherResponse.swift
>      let date: String
[NITS] dateDecodingStrategyを使ってDateで受け取ることもできます
https://developer.apple.com/documentation/foundation/jsondecoder/2895216-datedecodingstrategy

2022-03-30 04:38 UTC, novr commented on Yumemi-ios-training/Yumemi-ios-training/Model/WeatherResponse.swift
> +        case maxTemp = "max_temp"
[NITS] keyDecodingStrategyでスネークケースの対応もできます
https://developer.apple.com/documentation/foundation/jsondecoder/2949119-keydecodingstrategy

2022-03-30 04:38 UTC, novr commented on Yumemi-ios-training/Yumemi-ios-training/Presenter/WeatherPresenter.swift
> +        dateFormatter.dateFormat = "yyyy-MM-dd'T'HH:mm:ssZZZZZ"
[IMO] iPhoneのカレンダーを和暦やタイ暦に変更してみましょう

| ![image](https://user-images.githubusercontent.com/47618299/160752152-34e946b6-0adf-4f59-b8a3-4431c3bf2c5d.png) | ![image](https://user-images.githubusercontent.com/47618299/160752174-d6ebe5af-eb19-40dd-8c69-db5faf67d196.png) |

2022-03-30 04:38 UTC, novr commented on Yumemi-ios-training/Yumemi-ios-training/Presenter/WeatherPresenter.swift
> +    func showDate(date: Date)  // 要件には無いが日付を表示するためのDelegateメソッド
[IMO] dateはWeatherResponseに含まれているので別の更新サイクルにはならないかと

2022-03-30 05:49 UTC, KaitoKudou commented on Yumemi-ios-training/Yumemi-ios-training/Presenter/WeatherPresenter.swift
> +        dateFormatter.dateFormat = "yyyy-MM-dd'T'HH:mm:ssZZZZZ"
```
和暦：4038-04-01 03:00:00 +0000
タイ暦：1477-04-01 03:00:00 +0000
```
表示が変わってしまいました...

2022-03-30 05:57 UTC, daichikuwa0618 reviewed
この Session でやる課題内容がわからないので、 PR の概要に Session に対応する課題へのリンクだったり、求められている仕様が書いてあるとレビューしやすいと感じます。

---

[FYI]
例えば業務だと、

- デザインへのリンク
- API 仕様へのリンク
- 仕様書へのリンク

辺りは付けます。

2022-03-30 14:17 UTC, ykws requested changes

2022-03-30 14:17 UTC, ykws commented on Yumemi-ios-training/Yumemi-ios-training/Model/WeatherFetcher.swift
> +            let jsonString = try YumemiWeather.fetchWeather(#"{"area": "tokyo", "date": "2020-04-01T12:00:00+09:00" }"#)
![must-badge](https://img.shields.io/badge/review-must-red.svg)

Session5 を含めるということなので、以下についても Codable を適用してみましょう。
（Session4 ならリクエストはこの内容で OK です）

> Codableの仕組みを利用して、YumemiWeatherのAPIのパラメータを作成する

2022-03-30 14:17 UTC, ykws commented on Yumemi-ios-training/Yumemi-ios-training/Model/WeatherFetcher.swift
> +            let model = try parseJson(with: jsonString)
![imo-badge](https://img.shields.io/badge/review-imo-orange.svg)

ここで throw されると fatalError になり、 API に依存する部分なので alert 表示に流せる方が安全です。
研修の API が静的なものなのでそれを踏まえてあり得ないケースとして扱っているならこのままでも正しいです。

2022-03-30 14:17 UTC, ykws commented on Yumemi-ios-training/Yumemi-ios-training/Presenter/WeatherPresenter.swift
> +            case .jsonParseError:
`.jsonParseError` は `error` としてあり得そうでしょうか？
`fetchWeather` の中で `fatalError` になって `.failure` としては返ってこなそう？

2022-03-31 05:15 UTC, KaitoKudou commented on Yumemi-ios-training/Yumemi-ios-training/Presenter/WeatherPresenter.swift
> +            case .jsonParseError:
@ykws 
decodeで失敗する可能性があるかなと思って、パースエラーを表すjsonParseErrorを定義しました。
WeatherFetcherクラスのfetchWeaherメソッド内で
`guard let model = parseJson(with: weatherData) else { return .failure(.jsonParseError) }`
と書けば`.failure`として返るのではと考えました。

2022-03-31 05:25 UTC, KaitoKudou commented on Yumemi-ios-training/Yumemi-ios-training/Presenter/WeatherPresenter.swift
> +            case .jsonParseError:
@ykws 
model内に
`guard let model = parseJson(with: weatherData) else { return .failure(.jsonParseError) }`
上記のコードを追加し、わざとdecodeで失敗させた際に`.failure`として返り、ViewにもAlertで表示ができました。
<img width="370" alt="スクリーンショット 2022-03-31 14 24 18" src="https://user-images.githubusercontent.com/40165303/160982466-12ad8a65-27ca-4c0e-9def-bf94380c59e7.png">


> ここで throw されると fatalError になり、 API に依存する部分なので alert 表示に流せる方が安全です。
> 研修の API が静的なものなのでそれを踏まえてあり得ないケースとして扱っているならこのままでも正しいです。

このコメントに対する修正も一緒にさせていただきました。

2022-03-31 05:57 UTC, novr commented on Yumemi-ios-training/Yumemi-ios-training/Model/WeatherFetcher.swift
> +        let today: String = {
JSONEncoderもdateEncodingStrategyが使えます
https://developer.apple.com/documentation/foundation/jsonencoder/2895363-dateencodingstrategy

2022-03-31 06:17 UTC, KaitoKudou commented on Yumemi-ios-training/Yumemi-ios-training/Model/WeatherFetcher.swift
> +        let today: String = {
なるほど！
JSONDecoderにも似たようなものがありましたね。
ありがとうございます！

2022-03-31 07:59 UTC, novr commented on Yumemi-ios-training/Yumemi-ios-training/Model/WeatherFetcher.swift
> +            formatter.locale = Locale(identifier: "en_US_POSIX")
[IMO] ISO8601DateFormatter
https://developer.apple.com/documentation/foundation/iso8601dateformatter

またはdateEncodingStrategy = .iso8601
https://developer.apple.com/documentation/foundation/jsonencoder/dateencodingstrategy/iso8601

2022-03-31 07:59 UTC, novr commented on Yumemi-ios-training/Yumemi-ios-training/Model/WeatherFetcher.swift
> +            guard let jsonString = String(data: request, encoding: .utf8) else { return .failure(.jsonEncodeError) }
[IMO] parseJsonがあるのでまとめてencodeJsonに切り出してもよいかと

2022-03-31 07:59 UTC, novr commented on Yumemi-ios-training/Yumemi-ios-training/Model/WeatherFetcher.swift
> +    func parseJson(with jsonString: String) -> WeatherResponse? {
[IMO]
```suggestion
    func parseJson(with jsonString: String) throws -> WeatherResponse {
```
`return nil`でなく、`throw jsonDecodeError`できる

2022-03-31 08:17 UTC, ykws reviewed
良さそうです。あと古宮さんの指摘箇所を見直してみてもらえればと思います。

2022-03-31 08:17 UTC, ykws commented on Yumemi-ios-training/Yumemi-ios-training/Presenter/WeatherPresenter.swift
> +                view?.showErrorAlert(with: error.errorDescription)
![imo-badge](https://img.shields.io/badge/review-imo-orange.svg)

この内容なら switch しなくても良さそうですかね

```suggestion
            view?.showErrorAlert(with: error.errorDescription)
```

2022-03-31 08:17 UTC, ykws commented on Yumemi-ios-training/Yumemi-ios-training/Model/WeatherRequest.swift
> +struct WeatherRequest: Codable {
![imo-badge](https://img.shields.io/badge/review-imo-orange.svg)

encode しかしないので Encodable でも大丈夫です

2022-04-04 02:46 UTC, novr requested changes

2022-04-04 02:46 UTC, novr commented on Yumemi-ios-training/Yumemi-ios-training/Model/WeatherFetcher.swift
> +            return .failure(JsonError(error: error))
[MUST] JsonErrorからJsonErrorへの変換は不用です

2022-04-04 02:46 UTC, novr commented on Yumemi-ios-training/Yumemi-ios-training/Model/JsonError.swift
> +    init(error: Self) {
[IMO] 同型の変換なので不用なinitです

2022-04-04 02:46 UTC, novr commented on Yumemi-ios-training/Yumemi-ios-training/Model/WeatherFetcher.swift
> +        let request = try encoder.encode(request)
[ASK] try encoder.encodeでerrorになった場合はjsonEncodeErrorでなくEncodingErrorが発生し、fetchWeaherでfatalErrorとなりますが、想定されている処理でしょうか？
https://developer.apple.com/documentation/foundation/jsonencoder/2895034-encode

2022-04-04 02:46 UTC, novr commented on Yumemi-ios-training/Yumemi-ios-training/Model/JsonError.swift
> +    case jsonEncodeError
[IMO] APIErrorとJsonErrorに分けていますが、WeatherFetchableのErrorとしてまとめてしまってもよいかと

2022-04-04 03:00 UTC, KaitoKudou commented on Yumemi-ios-training/Yumemi-ios-training/Model/WeatherFetcher.swift
> +        let request = try encoder.encode(request)
@novr 
想定していませんでした。
do - catchでjsonEncodeErrorを流すようにします。

2022-04-04 03:06 UTC, KaitoKudou commented on Yumemi-ios-training/Yumemi-ios-training/Model/JsonError.swift
> +    case jsonEncodeError
@novr 
WeatherFetchableのErrorとしてまとめるというのは、どういうことでしょうか？

2022-04-04 03:17 UTC, novr commented on Yumemi-ios-training/Yumemi-ios-training/Model/JsonError.swift
> +    case jsonEncodeError
View側からはModelの先がAPIかどうかは気にする必要はないので
WeatherFetchableを呼んだ結果として、エラーはどんなものがあるかで考えるといいです
例としてはjsonEncodeErrorはinvalidParameterErrorとほぼ同じ意味(入力されたパラメータに問題がある)になりますよね

2022-04-04 05:17 UTC, KaitoKudou commented on Yumemi-ios-training/Yumemi-ios-training/Model/JsonError.swift
> +    case jsonEncodeError
@novr 
View側（ユーザ側）からどう見えるかですかね。
「JSONのEncode時にエラーがエラーが起きたよ」とAlertで出されてもユーザからすると何していいか分からないかもなと思いました。
そうなると、ユーザ側から見るとDecode時のエラーは予期せぬエラー(.unknownError)となりそうかなと思いました。

2022-04-04 07:05 UTC, novr requested changes

2022-04-04 07:05 UTC, novr commented on Yumemi-ios-training/Yumemi-ios-training/Model/WeatherFetcher.swift
>              fatalError("天気情報取得時に予期せぬエラーが発生：\(error.localizedDescription)")
encodeJsonやdecodeJsonでエラーの場合、fatalErrorが発生します

2022-04-04 07:05 UTC, novr commented on Yumemi-ios-training/Yumemi-ios-training/Model/WeatherFetcher.swift
> +    func fetchWeaher() -> Result<WeatherResponse, APIError>
[typo] 
```suggestion
    func fetchWeather() -> Result<WeatherResponse, APIError>
```

2022-04-04 13:44 UTC, novr approved these changes
![LGTM](https://image.lgtmoon.dev/95042)

2022-04-05 01:35 UTC, merged