Session/8
KaitoKudou/Yumemi-iOS-Training pull request #6
Opened 2022-04-07 03:18 UTC by KaitoKudou

# やったこと
- 取得した天気予報の結果によって、意図した画像が表示されるか確かめるテストコードを追加
  - 天気予報がsunnyだったら、画面に晴れ画像が表示されること
  - 天気予報がcloudyだったら、画面に曇り画像が表示されること
  - 天気予報がrainyだったら、画面に雨画像が表示されること
- 最高気温と最低気温がUILabelに反映されているか確かめるテストコードを追加

# 課題へのリンク
- [session8](https://github.com/yumemi-inc/ios-training/blob/main/Documentation/UnitTest.md)

# API 仕様へのリンク
- [YumemiWeather](https://github.com/yumemi-inc/ios-training/blob/main/Documentation/YumemiWeather.md)

# 実行画面
今回はテストコードの課題のため、実行画面なし

2022-04-07 04:04 UTC, el-hoshino requested changes
Swiftの命名規則的に、`JSON` は通常 `Json` のような単語として使うわけではないので、全部大文字か全部小文字にした方がいいですね、本家の `JSONEncoder` みたいに（[参考](https://www.swift.org/documentation/api-design-guidelines/#general-conventions)）

また、基本的にはテストを書くために本体の動きを変更するのは、どっちかというと本末転倒です、テストは本体の動きを保証するためのものですので（もちろんテスト書きやすいようにリファクタリングするのはアリですよ）

ちなみに私なら、`WeatherFetcher` に `encodeJSON` や `decodeJSON` みたいなメソッドを作らずに、自分用の `jsonEncoder` や `jsonDecoder` を作って保持して、必要なエンコードデコード作業をそのプロパティーに任せて、テストではそのプロパティーの動作を確認するように作るかな

```swift
class WeathcerFetcher {
    // ...
    let jsonEncoder: JSONEncoder
    // ...
    init() {
        // ...
        let encoder = JSONEncoder()
        // ...
        self.jsonEncoder = encoder
        // ...
    }
    // ...
}
```

```swift
class WeathcerFetcherTests: XCTestCase {
    // ...
    func test_weatherFetcherJSONEncoder() {
        let encoder = weathcerFetcher.encoder
        // ...
    }
}
```

2022-04-07 04:04 UTC, el-hoshino commented on Yumemi-ios-training/Yumemi-ios-trainingTests/JsonParserTests.swift
> +    }
これ、 `JsonParserMock` の動作のテストになってませんか？ 😅 
多分本来は `WeatherFetcher` の動作をテストしたいはずかと 😅

2022-04-07 04:04 UTC, el-hoshino commented on Yumemi-ios-training/Yumemi-ios-training/Presenter/WeatherPresenter.swift
> +    var model: WeatherFetchable
これ `var` にする必要はないかと 🤔

2022-04-07 06:23 UTC, KaitoKudou commented on Yumemi-ios-training/Yumemi-ios-trainingTests/JsonParserTests.swift
> +    }
@el-hoshino 
> ちなみに私なら、WeatherFetcher に encodeJSON や decodeJSON みたいなメソッドを作らずに、自分用の jsonEncoder や jsonDecoder を作って保持して、必要なエンコードデコード作業をそのプロパティーに任せて、テストではそのプロパティーの動作を確認するように作るかな

史さんが提案してくださった方法だと、WeatherFetcherクラスのfetchWeather()にエンコードとデコードの処理を書くことになりそうで、fetchWeather()の責務が多くなりそう(fetchと名前が付いてるのにパース処理も行う)だと感じたのですがどうなんでしょうか？

2022-04-07 06:52 UTC, KaitoKudou commented on Yumemi-ios-training/Yumemi-ios-trainingTests/JsonParserTests.swift
> +    }
エンコードデコード作業をプロパティで持つと全体的にコード量が減りそうですね

2022-04-07 06:55 UTC, el-hoshino commented on Yumemi-ios-training/Yumemi-ios-trainingTests/JsonParserTests.swift
> +    }
そもそも今の段階で既に `fetchWeather()` の中でエンコードデコード処理してますので、責務が増えたわけではないです 🙋 

じゃあ `fetchWeather()` の中でエンコードデコードすること自体が責務過多かどうかって話ですと、これは結構案件の規模によるかなという認識です；例えば `fetchWeather` の結果としてすぐに処理できる天気情報が欲しい、という考え方でしたら、この中でエンコードデコードしても問題ないというか、むしろ生の情報から実際に使える天気情報に変換するプロセスをメソッド内に閉じてるので、生の情報の構造が変わったとしても外に影響がない、という風にもなります；逆にそうじゃなくて生の情報が欲しいであればもちろん生のJSONデータを渡すのもアリと言えばアリです、ここら辺は結構案件によって変わります。自分が提案したのはあくまで既存の処理と同じ責務に留めた場合ですね

2022-04-07 17:38 UTC, el-hoshino approved these changes
![LGTM](https://i.lgtm.fun/1gvq.png)

2022-04-08 01:32 UTC, yumemi-sishigaki approved these changes
![LGTM](https://i.lgtm.fun/1w6s.png)

2022-04-08 05:14 UTC, merged