Session10
KaitoKudou/Yumemi-iOS-Training pull request #8
Opened 2022-04-11 10:38 UTC by KaitoKudou

# やったこと
- Delegateパターンを適用

# 課題へのリンク
- [session10](https://github.com/yumemi-inc/ios-training/blob/main/Documentation/Delegate.md)

# API 仕様へのリンク
- [YumemiWeather](https://github.com/yumemi-inc/ios-training/blob/main/Documentation/YumemiWeather.md)

# 実行画面
今回はなし

2022-04-11 13:44 UTC, ykws requested changes
![must-badge](https://img.shields.io/badge/review-must-red.svg)

テストが失敗しているので見直しをお願いします。

![ask-badge](https://img.shields.io/badge/review-ask-yellowgreen.svg)

model のパラメータを削除したのはどういった動機になりますか？

例えば、 Delegateパターンであることをわかりやすくするなら、
[UITableView の delegate property](https://developer.apple.com/documentation/uikit/uitableview/1614894-delegate) と同じような形で、現状のプログラムにおけて `delegate` property に相当する部分を Rename して、 `xxx.delegate = self` のような書き方で委譲させてみても良いかもしれません。

2022-04-12 02:42 UTC, KaitoKudou commented
@ykws 
> model のパラメータを削除したのはどういった動機になりますか？

ViewでPresenterのインスタンスを生成する際に、modelのパラメータを記述するのは違和感があるなと思ってmodelのパラメータを消しました。（「Viewなのに本来関係ないはずのModelを記述してしまったな」　みたいに感じました。）

2022-04-12 07:02 UTC, yumemi-sishigaki approved these changes
![LGTM](https://i.lgtm.fun/1gfh.png)

2022-04-12 07:02 UTC, yumemi-sishigaki commented on Yumemi-ios-training/Yumemi-ios-trainingTests/WeatherViewTests.swift
> +            XCTAssertEqual(error.errorDescription, R.string.message.unknownError())
Rswiftはうちの案件でもよく使われてるんでよく使いましょう🙋‍♀️

2022-04-12 07:03 UTC, novr commented on Yumemi-ios-training/Yumemi-ios-trainingTests/WeatherViewTests.swift
>          switch stub.fetchWeather() {
[IMO] stub.fetchWeatherをする必要がなく
`viewController?.showWeather(weatherResponse: WeatherResponse(weather: .sunny, maxTemp: 0, minTemp: 0, date: Date()))`と同じです

Viewクラスのテストならば
- 外部入力(ユーザアクション)メソッドが呼ばれたら、WeatherPresenterProtocolInputのメソッドが呼ばれる事
- WeatherPresenterProtocolOutputにあるメソッドの動作検証
等が対象になります

Session内容と違いますので別途対応で

2022-04-12 07:03 UTC, novr commented on Yumemi-ios-training/Yumemi-ios-training/Presenter/WeatherPresenter.swift
> +    init() {
[IMO] ModelもInjection可能な方がテストが容易です

2022-04-12 07:03 UTC, novr commented on Yumemi-ios-training/Yumemi-ios-training/Presenter/WeatherPresenter.swift
> +    weak var delegate: WeatherPresenterProtocolOutput?
Session delegateの内容としてはすでに実施済みでしたね

2022-04-12 15:36 UTC, ykws approved these changes
テスト修復されていることを確認できました！
Delegate の理解も Rename により明確で良いと思います。

![LGTM](https://image.lgtmoon.dev/28333)

> ViewでPresenterのインスタンスを生成する際に、modelのパラメータを記述するのは違和感があるなと思ってmodelのパラメータを消しました。（「Viewなのに本来関係ないはずのModelを記述してしまったな」　みたいに感じました。）

Model の注入については以下のコメントにもあるように別途テストしやすさについて検討してもらうと良いかなと思います。

https://github.com/KaitoKudou/Yumemi-iOS-Training/pull/8/files#r848051142

2022-04-13 10:28 UTC, merged